name: Docker CI

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]
    release:
      types: published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Login to Docker
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Build and Push Docker image (Docker CLI is pre-installed in GitHub-hosted runners)
      - name: Build and Push Docker Image (Pull Request)
        run: |

          # Build the Docker image
          docker build --provenance=true --sbom=true -t ${{ vars.DOCKERHUB_USERNAME }}/hostname-webapp:dev .

          # Push the Docker image to Docker Hub
          docker push ${{ vars.DOCKERHUB_USERNAME }}/hostname-webapp:dev
        if: github.event_name == 'pull_request'

      - name: Build and Push Docker Image (Push)
        run: |

          # Build the Docker image
          docker build -t ${{ vars.DOCKERHUB_USERNAME }}/hostname-webapp:latest .

          # Push the Docker image to Docker Hub
          docker push ${{ vars.DOCKERHUB_USERNAME }}/hostname-webapp:latest
        if: github.event_name == 'push'

      - name: Build and Push Docker Image (Release)
        run: |

          # Build the Docker image
          docker build -t ${{ vars.DOCKERHUB_USERNAME }}/hostname-webapp:${{ github.event.release.tag_name }} .

          # Push the Docker image to Docker Hub
          docker push ${{ vars.DOCKERHUB_USERNAME }}/hostname-webapp:${{ github.event.release.tag_name }}
        if: github.event_name == 'release'